name: Daily Database Dump

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  dump-db:
    runs-on: ubuntu-latest

    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +%Y-%m-%d_%H-%M)" >> $GITHUB_ENV
      - name: Use pg-dump action
        uses: tj-actions/pg-dump@v3
        with:
          database_url: "${{ secrets.DATABASE_URL }}"
          path: "backup_${{ env.NOW }}.sql"
          postgresql_version: "16"
          options: "--no-acl --no-owner"
      - name: Upload dump as artifact
        uses: actions/upload-artifact@v3
        with:
          name: database-dump
          path: "backup_${{ env.NOW }}.sql"
